# Name:        tag-release.yaml
# Author:      Mathew Fleisch <mathew.fleisch@gmail.com>
# Description: This action will build and push a docker container, when triggered by
#              pushing a new git tag (that starts with the letter 'v').
name: Release Bashbot
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Push Bashbot Container
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        name: Set tag
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          echo "tag: ${{ steps.vars.outputs.tag }}"
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      -
        name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: mathewfleisch/bashbot:latest,mathewfleisch/bashbot:${{ steps.vars.outputs.tag }}

  # Release bashbot go-binaries once the docker container is built and pushed.
  release:
    name: Release Bashbot Binaries ${{ matrix.platform }}
    needs: build
    strategy:
      fail-fast: true
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        name: Set tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/} && echo ${{ steps.vars.outputs.tag }}
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}}
      -
        name: Build go-binaries
        run: |
          make build
          GOARCH=arm64 make build

      -
        name: Cut Github Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GIT_TOKEN }}
          allowUpdates: true
          artifacts: "bin/*"




